[package]
name = "pyro"
version = "0.0.0"
edition = "2021"

[features]

[dependencies]
ref-cast = "1.0"
sealed = "0.3"
slotmap = "1.0"
tuple_list = "0.1"

[dev-dependencies]
criterion = { version = "0.3", features = [ "async_tokio" ] }
