name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Specify how to bump the version for `hydroflow` crates. Does not affect dependencies."
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
          - keep
          - auto
      execute:
        description: "Actually execute and publish the release?"
        required: true
        type: boolean
        default: false

jobs:
  wait_ci:
    name: Wait for CI success
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: "CI"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  release_job:
    name: Release Job
    needs: wait_ci
    if: ${{ needs.wait_ci.result == 'success' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version bump: $BUMP"
          echo "Execute: $EXECUTE"
        env:
          BUMP: ${{ inputs.bump }}
          EXECUTE: ${{ inputs.execute }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Install cargo-smart-release
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-smart-release

      - name: Cargo smart-release
        uses: actions-rs/cargo@v1
        with:
          command: smart-release
          args: --update-crates-index --no-changelog-preview --bump patch --bump-dependencies auto --no-bump-on-demand "$EXECUTE_ARG" hydroflow hydroflow_*
        env:
          EXECUTE_ARG: ${{ inputs.execute && '--execute' || '--no-publish' }}
